spring.application.name=game-info-app
server.port=8080
server.error.whitelabel.enabled=false

game.api.base-url=${GAME_API_BASE_URL:https://api.rawg.io/api}
game.api.key=ae85778c7c1a48faaa0cbc5e58e5742e
game.api.search-path=${GAME_API_SEARCH_PATH:/games}
